/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lukra
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }
    double valor1,valor2;
    String sinal;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        JBN_Zero = new javax.swing.JButton();
        JBN_UM = new javax.swing.JButton();
        JBN_Dois = new javax.swing.JButton();
        JBN_Tres = new javax.swing.JButton();
        JBN_Quatro = new javax.swing.JButton();
        JBN_Cinco = new javax.swing.JButton();
        JBN_Seis = new javax.swing.JButton();
        JBN_Sete = new javax.swing.JButton();
        JBN_Oito = new javax.swing.JButton();
        JBN_Nove = new javax.swing.JButton();
        JBN_Igualdade = new javax.swing.JButton();
        JBN_Multiplicacao = new javax.swing.JButton();
        JBN_Divisao = new javax.swing.JButton();
        JBN_Diminuicao = new javax.swing.JButton();
        JBN_Soma = new javax.swing.JButton();
        JTXT_Calculos = new javax.swing.JTextField();
        JLBL_Nome_do_Aplicativo = new javax.swing.JLabel();
        JBN_Limpar = new javax.swing.JButton();
        JBN_Ponto = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JBN_Zero.setBackground(new java.awt.Color(51, 204, 255));
        JBN_Zero.setText("0");
        JBN_Zero.setPreferredSize(new java.awt.Dimension(40, 40));
        JBN_Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_ZeroActionPerformed(evt);
            }
        });

        JBN_UM.setBackground(new java.awt.Color(51, 204, 255));
        JBN_UM.setText("1");
        JBN_UM.setPreferredSize(new java.awt.Dimension(40, 40));
        JBN_UM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_UMActionPerformed(evt);
            }
        });

        JBN_Dois.setBackground(new java.awt.Color(51, 204, 255));
        JBN_Dois.setText("2");
        JBN_Dois.setPreferredSize(new java.awt.Dimension(40, 40));
        JBN_Dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_DoisActionPerformed(evt);
            }
        });

        JBN_Tres.setBackground(new java.awt.Color(51, 204, 255));
        JBN_Tres.setText("3");
        JBN_Tres.setPreferredSize(new java.awt.Dimension(40, 40));
        JBN_Tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_TresActionPerformed(evt);
            }
        });

        JBN_Quatro.setBackground(new java.awt.Color(51, 204, 255));
        JBN_Quatro.setText("4");
        JBN_Quatro.setPreferredSize(new java.awt.Dimension(40, 40));
        JBN_Quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_QuatroActionPerformed(evt);
            }
        });

        JBN_Cinco.setBackground(new java.awt.Color(51, 204, 255));
        JBN_Cinco.setText("5");
        JBN_Cinco.setPreferredSize(new java.awt.Dimension(40, 40));
        JBN_Cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_CincoActionPerformed(evt);
            }
        });

        JBN_Seis.setBackground(new java.awt.Color(51, 204, 255));
        JBN_Seis.setText("6");
        JBN_Seis.setPreferredSize(new java.awt.Dimension(40, 40));
        JBN_Seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_SeisActionPerformed(evt);
            }
        });

        JBN_Sete.setBackground(new java.awt.Color(0, 204, 255));
        JBN_Sete.setText("7");
        JBN_Sete.setMaximumSize(new java.awt.Dimension(40, 40));
        JBN_Sete.setMinimumSize(new java.awt.Dimension(40, 40));
        JBN_Sete.setPreferredSize(new java.awt.Dimension(40, 40));
        JBN_Sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_SeteActionPerformed(evt);
            }
        });

        JBN_Oito.setBackground(new java.awt.Color(51, 204, 255));
        JBN_Oito.setText("8");
        JBN_Oito.setMaximumSize(new java.awt.Dimension(40, 40));
        JBN_Oito.setMinimumSize(new java.awt.Dimension(40, 40));
        JBN_Oito.setPreferredSize(new java.awt.Dimension(40, 40));
        JBN_Oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_OitoActionPerformed(evt);
            }
        });

        JBN_Nove.setBackground(new java.awt.Color(51, 204, 255));
        JBN_Nove.setText("9");
        JBN_Nove.setPreferredSize(new java.awt.Dimension(40, 40));
        JBN_Nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_NoveActionPerformed(evt);
            }
        });

        JBN_Igualdade.setBackground(new java.awt.Color(51, 204, 255));
        JBN_Igualdade.setText("=");
        JBN_Igualdade.setPreferredSize(new java.awt.Dimension(40, 20));
        JBN_Igualdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_IgualdadeActionPerformed(evt);
            }
        });

        JBN_Multiplicacao.setBackground(new java.awt.Color(51, 204, 255));
        JBN_Multiplicacao.setText("*");
        JBN_Multiplicacao.setPreferredSize(new java.awt.Dimension(40, 40));
        JBN_Multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_MultiplicacaoActionPerformed(evt);
            }
        });

        JBN_Divisao.setBackground(new java.awt.Color(51, 204, 255));
        JBN_Divisao.setText("/");
        JBN_Divisao.setPreferredSize(new java.awt.Dimension(40, 40));
        JBN_Divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_DivisaoActionPerformed(evt);
            }
        });

        JBN_Diminuicao.setBackground(new java.awt.Color(51, 204, 255));
        JBN_Diminuicao.setText("-");
        JBN_Diminuicao.setPreferredSize(new java.awt.Dimension(40, 40));
        JBN_Diminuicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_DiminuicaoActionPerformed(evt);
            }
        });

        JBN_Soma.setBackground(new java.awt.Color(51, 204, 255));
        JBN_Soma.setText("+");
        JBN_Soma.setPreferredSize(new java.awt.Dimension(40, 40));
        JBN_Soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_SomaActionPerformed(evt);
            }
        });

        JTXT_Calculos.setEditable(false);
        JTXT_Calculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTXT_CalculosActionPerformed(evt);
            }
        });

        JLBL_Nome_do_Aplicativo.setBackground(new java.awt.Color(153, 255, 255));
        JLBL_Nome_do_Aplicativo.setForeground(new java.awt.Color(0, 0, 255));
        JLBL_Nome_do_Aplicativo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBL_Nome_do_Aplicativo.setText("CALCULADORA");

        JBN_Limpar.setBackground(new java.awt.Color(51, 204, 255));
        JBN_Limpar.setText("C");
        JBN_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_LimparActionPerformed(evt);
            }
        });

        JBN_Ponto.setBackground(new java.awt.Color(51, 204, 255));
        JBN_Ponto.setText(".");
        JBN_Ponto.setPreferredSize(new java.awt.Dimension(40, 40));
        JBN_Ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_PontoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTXT_Calculos)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBN_Quatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBN_Cinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JBN_UM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(JBN_Dois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JBN_Zero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(JBN_Ponto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBN_Sete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBN_Oito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(JBN_Seis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JBN_Tres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBN_Igualdade, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(JBN_Nove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBN_Diminuicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBN_Soma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBN_Multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBN_Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLBL_Nome_do_Aplicativo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBN_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLBL_Nome_do_Aplicativo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBN_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTXT_Calculos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBN_Nove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBN_Sete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBN_Oito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBN_Seis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JBN_Tres, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(JBN_Quatro, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                        .addComponent(JBN_Cinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(JBN_UM, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JBN_Dois, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JBN_Zero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBN_Ponto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBN_Igualdade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBN_Soma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15)
                        .addComponent(JBN_Diminuicao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBN_Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBN_Multiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBN_ZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_ZeroActionPerformed
        // TODO add your handling code here:
        JTXT_Calculos.setText(JTXT_Calculos.getText()+"0");
    }//GEN-LAST:event_JBN_ZeroActionPerformed

    private void JBN_DoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_DoisActionPerformed
        // TODO add your handling code here:
        JTXT_Calculos.setText(JTXT_Calculos.getText()+"2");
    }//GEN-LAST:event_JBN_DoisActionPerformed

    private void JBN_CincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_CincoActionPerformed
        // TODO add your handling code here:
        JTXT_Calculos.setText(JTXT_Calculos.getText()+"5");
    }//GEN-LAST:event_JBN_CincoActionPerformed

    private void JBN_OitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_OitoActionPerformed
        // TODO add your handling code here:
        JTXT_Calculos.setText(JTXT_Calculos.getText()+"8");
    }//GEN-LAST:event_JBN_OitoActionPerformed

    private void JBN_IgualdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_IgualdadeActionPerformed
        // TODO add your handling code here:
        valor2 = Double.parseDouble(JTXT_Calculos.getText());
        if(sinal == "soma"){
            JTXT_Calculos.setText(String.valueOf(valor1 + valor2));
        }
        if(sinal == "diminuicao"){
            JTXT_Calculos.setText(String.valueOf(valor1 - valor2));
        }
        if(sinal == "multiplicacao"){
            JTXT_Calculos.setText(String.valueOf(valor1 * valor2));
        }
        if(sinal == "divisao" && valor2 != 0){
            JTXT_Calculos.setText(String.valueOf(valor1 / valor2));
        }else if(sinal == "divisao" && valor2 == 0){
            JTXT_Calculos.setText("O gente já viu divisão por zero");
        }
    }//GEN-LAST:event_JBN_IgualdadeActionPerformed

    private void JBN_MultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_MultiplicacaoActionPerformed
        // TODO add your handling code here:
        valor1 = Double.parseDouble(JTXT_Calculos.getText());
        JTXT_Calculos.setText("");
        sinal = "multiplicacao";
        
    }//GEN-LAST:event_JBN_MultiplicacaoActionPerformed

    private void JBN_TresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_TresActionPerformed
        // TODO add your handling code here:
        JTXT_Calculos.setText(JTXT_Calculos.getText()+"3");
    }//GEN-LAST:event_JBN_TresActionPerformed

    private void JBN_QuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_QuatroActionPerformed
        // TODO add your handling code here:
        JTXT_Calculos.setText(JTXT_Calculos.getText()+"4");
    }//GEN-LAST:event_JBN_QuatroActionPerformed

    private void JBN_SomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_SomaActionPerformed
        // TODO add your handling code here:
        valor1 = Double.parseDouble(JTXT_Calculos.getText());
        JTXT_Calculos.setText("");
        sinal = "soma";
    }//GEN-LAST:event_JBN_SomaActionPerformed

    private void JBN_UMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_UMActionPerformed
        // TODO add your handling code here:
        JTXT_Calculos.setText(JTXT_Calculos.getText()+"1");
    }//GEN-LAST:event_JBN_UMActionPerformed

    private void JBN_SeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_SeisActionPerformed
        // TODO add your handling code here:
        JTXT_Calculos.setText(JTXT_Calculos.getText()+"6");
    }//GEN-LAST:event_JBN_SeisActionPerformed

    private void JBN_SeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_SeteActionPerformed
        // TODO add your handling code here:
        JTXT_Calculos.setText(JTXT_Calculos.getText()+"7");
    }//GEN-LAST:event_JBN_SeteActionPerformed

    private void JBN_NoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_NoveActionPerformed
        // TODO add your handling code here:
        JTXT_Calculos.setText(JTXT_Calculos.getText()+"9");
    }//GEN-LAST:event_JBN_NoveActionPerformed

    private void JBN_DiminuicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_DiminuicaoActionPerformed
        // TODO add your handling code here:
        valor1 = Double.parseDouble(JTXT_Calculos.getText());
        JTXT_Calculos.setText("");
        sinal = "diminuicao";
        
    }//GEN-LAST:event_JBN_DiminuicaoActionPerformed

    private void JBN_DivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_DivisaoActionPerformed
        // TODO add your handling code here:
        valor1 = Double.parseDouble(JTXT_Calculos.getText());
        JTXT_Calculos.setText("");
        sinal = "divisao";
    }//GEN-LAST:event_JBN_DivisaoActionPerformed

    private void JTXT_CalculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTXT_CalculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTXT_CalculosActionPerformed

    private void JBN_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_LimparActionPerformed
        // TODO add your handling code here:
        valor1 = 0;
        valor2 = 0;
        JTXT_Calculos.setText("");
    }//GEN-LAST:event_JBN_LimparActionPerformed

    private void JBN_PontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_PontoActionPerformed
        // TODO add your handling code here:
        JTXT_Calculos.setText(JTXT_Calculos.getText()+".");
    }//GEN-LAST:event_JBN_PontoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBN_Cinco;
    private javax.swing.JButton JBN_Diminuicao;
    private javax.swing.JButton JBN_Divisao;
    private javax.swing.JButton JBN_Dois;
    private javax.swing.JButton JBN_Igualdade;
    private javax.swing.JButton JBN_Limpar;
    private javax.swing.JButton JBN_Multiplicacao;
    private javax.swing.JButton JBN_Nove;
    private javax.swing.JButton JBN_Oito;
    private javax.swing.JButton JBN_Ponto;
    private javax.swing.JButton JBN_Quatro;
    private javax.swing.JButton JBN_Seis;
    private javax.swing.JButton JBN_Sete;
    private javax.swing.JButton JBN_Soma;
    private javax.swing.JButton JBN_Tres;
    private javax.swing.JButton JBN_UM;
    private javax.swing.JButton JBN_Zero;
    private javax.swing.JLabel JLBL_Nome_do_Aplicativo;
    private javax.swing.JTextField JTXT_Calculos;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
